"""Candidate representation and C++ source rendering for OptMirror evolution."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from hashlib import sha256
import json
import math

PROGRAM_OPS = (
    "hpwl_log",
    "degree_log",
    "mirror_entropy_temper",
    "fanout_shock_penalty",
    "hpwl_degree_cross",
    "deterministic_phase",
)

CODE_SNIPPETS = {
    "hpwl_log": "score += std::log1p(static_cast<double>(hpwl));",
    "degree_log": "score += 0.35 * std::log1p(static_cast<double>(degree));",
    "mirror_entropy_temper": (
        "const double entropy = std::log1p(static_cast<double>(degree));\n"
        "    score += std::log1p(static_cast<double>(hpwl)) / (1.0 + entropy);"
    ),
    "fanout_shock_penalty": (
        "if (degree > 8) {\n"
        "      score -= 0.20 * std::log1p(static_cast<double>(degree - 8));\n"
        "    }"
    ),
    "hpwl_degree_cross": (
        "score += 0.05 * std::sqrt(std::log1p(static_cast<double>(hpwl)))\n"
        "           * std::log1p(static_cast<double>(degree));"
    ),
    "deterministic_phase": "score += static_cast<double>(stable_id % 17) * 1e-9;",
}


@dataclass(frozen=True)
class MirrorPolicy:
    """A small generated C++ policy that only ranks legal mirror attempts.

    The upstream acceptance check and cell-edge spacing check are deliberately
    outside this policy. A candidate can therefore alter a non-commutative
    heuristic decision, but never approve an illegal action by itself.
    """

    hpwl_weight: float = 1.0
    degree_weight: float = 0.0
    enabled: bool = True
    program: tuple[str, ...] = field(default_factory=lambda: ("hpwl_log",))

    @classmethod
    def baseline(cls) -> "MirrorPolicy":
        """Return the stock algorithm: candidate order is not changed."""
        return cls(enabled=False, program=())

    def validate(self) -> None:
        for name, value in asdict(self).items():
            if name in ("enabled", "program"):
                continue
            if not math.isfinite(value) or abs(value) > 5.0:
                raise ValueError(f"{name} must be finite and in [-5, 5]")
        if type(self.program) is not tuple:
            raise ValueError("program must be an immutable tuple")
        if len(self.program) > 16:
            raise ValueError("program may contain at most 16 statements")
        for op in self.program:
            if op not in PROGRAM_OPS:
                raise ValueError(f"unknown program operation: {op}")
        if self.enabled and not self.program:
            raise ValueError("an enabled policy must contain generated code")

    @property
    def identifier(self) -> str:
        payload = json.dumps(self.to_dict(), sort_keys=True, separators=(",", ":"))
        return sha256(payload.encode()).hexdigest()[:12]

    def to_dict(self) -> dict[str, float | bool | list[str]]:
        return {
            "hpwl_weight": self.hpwl_weight,
            "degree_weight": self.degree_weight,
            "enabled": self.enabled,
            "program": list(self.program),
        }

    @classmethod
    def from_dict(cls, value: dict[str, float | bool | list[str]]) -> "MirrorPolicy":
        data = dict(value)
        if "program" not in data:
            data["program"] = [] if data.get("enabled") is False else ["hpwl_log"]
        data["program"] = tuple(data["program"])  # type: ignore[index]
        policy = cls(**data)
        policy.validate()
        return policy

    def _score_body(self) -> str:
        if not self.enabled:
            return "return 0.0;"
        lines = ["double score = 0.0;"]
        if self.hpwl_weight or self.degree_weight:
            lines += [
                f"score += {self.hpwl_weight:.17g} * std::log1p(static_cast<double>(hpwl));",
                f"score += {self.degree_weight:.17g} * std::log1p(static_cast<double>(degree));",
            ]
        for op in self.program:
            lines.append(CODE_SNIPPETS[op])
        lines.append("return score;")
        return "\n    ".join(lines)

    def to_header(self) -> str:
        """Render the only source file varied by the search.

        Using a generated header keeps a candidate reviewable (roughly 25
        lines), makes incremental builds cheap, and gives every archive record
        a direct source artifact rather than an opaque parameter list.
        """
        self.validate()
        enabled = "true" if self.enabled else "false"
        return f"""// Generated by openroad_evolution; candidate {self.identifier}.
// Do not edit: the experiment runner rewrites this file per candidate.
#pragma once

#include <cmath>
#include <cstdint>

namespace dpl {{
class EvolvedMirrorPolicy
{{
 public:
  static constexpr bool enabled() {{ return {enabled}; }}

  static double score(const int64_t hpwl,
                      const uint32_t degree,
                      const uint32_t stable_id)
  {{
    {self._score_body()}
  }}

  static bool isHigherPriority(const int64_t lhs_hpwl,
                               const uint32_t lhs_degree,
                               const uint32_t lhs_id,
                               const int64_t rhs_hpwl,
                               const uint32_t rhs_degree,
                               const uint32_t rhs_id)
  {{
    const double lhs_score = score(lhs_hpwl, lhs_degree, lhs_id);
    const double rhs_score = score(rhs_hpwl, rhs_degree, rhs_id);
    if (lhs_score != rhs_score) {{
      return lhs_score > rhs_score;
    }}
    return lhs_id < rhs_id;
  }}
}};
}}  // namespace dpl
"""
