"""Candidate representation and C++ source rendering for OptMirror evolution."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from hashlib import sha256
import json
import math


@dataclass(frozen=True)
class MirrorPolicy:
    """A small generated C++ policy that only ranks legal mirror attempts.

    The upstream acceptance check and cell-edge spacing check are deliberately
    outside this policy. A candidate can therefore alter a non-commutative
    heuristic decision, but never approve an illegal action by itself.
    """

    hpwl_weight: float = 1.0
    degree_weight: float = 0.0
    id_weight: float = 0.0
    enabled: bool = True

    @classmethod
    def baseline(cls) -> "MirrorPolicy":
        """Return the stock algorithm: candidate order is not changed."""
        return cls(enabled=False)

    def validate(self) -> None:
        for name, value in asdict(self).items():
            if name == "enabled":
                continue
            if not math.isfinite(value) or abs(value) > 100.0:
                raise ValueError(f"{name} must be finite and in [-100, 100]")
        if self.enabled and not any(
            (self.hpwl_weight, self.degree_weight, self.id_weight)
        ):
            raise ValueError("an enabled policy must have a non-zero weight")

    @property
    def identifier(self) -> str:
        payload = json.dumps(asdict(self), sort_keys=True, separators=(",", ":"))
        return sha256(payload.encode()).hexdigest()[:12]

    def to_dict(self) -> dict[str, float | bool]:
        return asdict(self)

    @classmethod
    def from_dict(cls, value: dict[str, float | bool]) -> "MirrorPolicy":
        policy = cls(**value)
        policy.validate()
        return policy

    def to_header(self) -> str:
        """Render the only source file varied by the search.

        Using a generated header keeps a candidate reviewable (roughly 25
        lines), makes incremental builds cheap, and gives every archive record
        a direct source artifact rather than an opaque parameter list.
        """
        self.validate()
        enabled = "true" if self.enabled else "false"
        return f"""// Generated by openroad_evolution; candidate {self.identifier}.
// Do not edit: the experiment runner rewrites this file per candidate.
#pragma once

#include <cstdint>

namespace dpl {{
class EvolvedMirrorPolicy
{{
 public:
  static constexpr bool enabled() {{ return {enabled}; }}

  static bool isHigherPriority(const int64_t lhs_hpwl,
                               const uint32_t lhs_degree,
                               const uint32_t lhs_id,
                               const int64_t rhs_hpwl,
                               const uint32_t rhs_degree,
                               const uint32_t rhs_id)
  {{
    constexpr double kHpwlWeight = {self.hpwl_weight:.17g};
    constexpr double kDegreeWeight = {self.degree_weight:.17g};
    constexpr double kIdWeight = {self.id_weight:.17g};
    const double lhs_score = kHpwlWeight * static_cast<double>(lhs_hpwl)
                           + kDegreeWeight * static_cast<double>(lhs_degree)
                           + kIdWeight * static_cast<double>(lhs_id);
    const double rhs_score = kHpwlWeight * static_cast<double>(rhs_hpwl)
                           + kDegreeWeight * static_cast<double>(rhs_degree)
                           + kIdWeight * static_cast<double>(rhs_id);
    if (lhs_score != rhs_score) {{
      return lhs_score > rhs_score;
    }}
    return lhs_id < rhs_id;
  }}
}};
}}  // namespace dpl
"""
